---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse, quietly = T)
library(lubridate)
library(stringr)
```

```{r}
col_spec <- cols(
  gameid = col_character(),
  url = col_character(),
  league = col_character(),
  split = col_character(),
  date = col_character(),
  week = col_double(),
  game = col_double(),
  patchno = col_double(),
  playerid = col_double(),
  side = col_character(),
  position = col_character(),
  player = col_character(),
  team = col_character(),
  champion = col_logical(),
  ban1 = col_character(),
  ban2 = col_character(),
  ban3 = col_character(),
  gamelength = col_double(),
  result = col_double(),
  k = col_double(),
  d = col_double(),
  a = col_double(),
  teamkills = col_double(),
  teamdeaths = col_double(),
  doubles = col_logical(),
  triples = col_logical(),
  quadras = col_logical(),
  pentas = col_logical(),
  fb = col_double(),
  fbvictim = col_double(),
  fbtime = col_double(),
  kpm = col_double(),
  okpm = col_double(),
  ckpm = col_double(),
  fd = col_double(),
  fdtime = col_double(),
  teamdragkills = col_double(),
  oppdragkills = col_double(),
  herald = col_double(),
  heraldtime = col_double(),
  ft = col_double(),
  fttime = col_double(),
  firsttothreetowers = col_double(),
  teamtowerkills = col_double(),
  opptowerkills = col_double(),
  fbaron = col_double(),
  fbarontime = col_double(),
  teambaronkills = col_double(),
  oppbaronkills = col_double(),
  dmgtochamps = col_double(),
  dmgtochampsperminute = col_double(),
  dmgshare = col_logical(),
  earnedgoldshare = col_logical(),
  wards = col_double(),
  wpm = col_double(),
  wardshare = col_double(),
  wardkills = col_double(),
  wcpm = col_double(),
  visionwards = col_double(),
  visionwardbuys = col_double(),
  visiblewardclearrate = col_double(),
  invisiblewardclearrate = col_double(),
  totalgold = col_double(),
  earnedgpm = col_double(),
  goldspent = col_double(),
  gspd = col_double(),
  minionkills = col_double(),
  monsterkills = col_double(),
  monsterkillsownjungle = col_double(),
  monsterkillsenemyjungle = col_double(),
  cspm = col_double(),
  csat10 = col_double(),
  oppcsat10 = col_double(),
  csdat10 = col_double(),
  goldat10 = col_double(),
  oppgoldat10 = col_double(),
  gdat10 = col_double(),
  goldat15 = col_double(),
  oppgoldat15 = col_double(),
  gdat15 = col_double(),
  xpat10 = col_double(),
  oppxpat10 = col_double(),
  xpdat10 = col_double()
)
full_16 <- read_csv(file = "data/16_full.csv", col_types = col_spec)

full_17 <- read_csv(file = "data/17_full.csv", col_types = col_spec)

sp_18 <- read_csv(file = "data/18_sp.csv", col_types = col_spec)

su_18 <- read_csv(file = "data/18_su.csv", col_types = col_spec)

sp_19 <- read_csv(file = "data/19_sp.csv", col_types = col_spec)
```

```{r}
lol_matches <- bind_rows(full_16, full_17, sp_18, su_18, sp_19) %>%
  mutate(
    league = case_when(
      league == "NALCS" ~ "LCS",
      league == "EULCS" ~ "LEC",
      league == "LCK" ~ "LCK",
      league == "LPL" ~ "LPL",
      league == "LCS" ~ "LCS",
      league == "LEC" ~ "LEC")
    ) %>%
  arrange(league, split)

write_csv(x = lol_matches, path = "data/lol_matches_16_19.csv")
```

